### PR TITLE
Added ITS_Study_Guide_V3_07_15_2021 folder for updated Expiration Tim…

### LINKED ISSUE #2: licenseAreaExtent field is using depecrated value in newly released study guide configs version ITS_Study_Guide_V3_07_15_2021
We are seeing some issues while running latest study guide configs for Tranche 1 from - 
[https://github.com/NTIA/sas-study-guide/tree/SASCBRS-210_Updated_ExpirationTime_FIPS/Published%20Study%20Guides/ITS_Study_Guide_V3_07_15_2021](url)

licenseAreaExtent field in below configs is pointing to deprecated value of “zone/census_tract/census/2010/<county_fips_code>”.
This field should now point to “zone/county/census/2017/<county_fips_code>”.

Similar fix was made in Test Harness code recently on top of v1.0.27
Reference to test harness issue + fix:
 ##https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/issues/901

List of T1 configs with deprecated value in licenseAreaExtent field -
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_Table-Mountain-03-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C75_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/23013",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C00_Nov_14_test_7_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/41005",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C00_Nov_14_test_7_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/53035",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C00_Nov_14_test_7_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/53053",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C04_multiple_protected_entities-sample_rev02_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/12031",
test_WINNF_FT_S_PPR_1/PPR-01_T1_C00_M_Bremerton_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/53035",
test_WINNF_FT_S_PPR_1/PPR-01_T1_C00_M_ Jacksonville_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/12031",
test_WINNF_FT_S_PPR_1/PPR-01_T1_C00_M_Norfolk_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/51710",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",

Thanks for your time for checking this.

### PR DESCRIPTION
**Pull request by cheroy-ntia**
…e and FIPS code config files

resolves #2

### CODE REVIEW

**Review by jodumkeNTIA — APPROVED** [review]
Is good, possibly 2 things missing(BPR2 / DPA File),  Please add if needed and merge branch this into master.


BPR2 is missing in modified T1 tests

Good job with FAD1/SIQ12/PPR2/MCP1 PALs, FAD1 (Seemingly no or hardly any Duplicate PAL Ids, and Only 2 PALS from different counties used in all FAD1/SIQ12 tests)

For IPR7, might want to include current p-dpa.kml file as this test is configurable for p-dpa:
    https://github.com/NTIA/METS/blob/sascbrs_148_create_mcp_config_generation_gui_with_no_backend_functionality_implemented/DatabaseSeeder/RawData/P-DPAs-1.0.9.kml

For MCP, a test name appears to have changed, but is ok:
    MCP-01_T1_C00_West1_test_7.config ->
    MCP-01_T1_C00_Nov_14_test_7_M3.config

**Comment by cheroy-ntia** [comment]
ITS_Study_Guide_V3_07_15_2021\test_WINNF_FT_S_BPR_2 is in the repository

MCP-01_T1_C00_Nov_14_test_7.config is in
\\itsfs01\Projects\3_5GHzEscSasCertification\Files for Tranch1 (configs - study guide)\test_WINNF_FT_S_MCP_1
Would you like to rename it to MCP-01_T1_C00_West1_test_7.config?

**Comment by jodumkeNTIA** [comment]
> 
> 
> ITS_Study_Guide_V3_07_15_2021\test_WINNF_FT_S_BPR_2 is in the repository
> 
> MCP-01_T1_C00_Nov_14_test_7.config is in
> \itsfs01\Projects\3_5GHzEscSasCertification\Files for Tranch1 (configs - study guide)\test_WINNF_FT_S_MCP_1
> Would you like to rename it to MCP-01_T1_C00_West1_test_7.config?

It's upto you, I think the newer name is good.

**Comment by jodumkeNTIA** [comment]
> 
> 
> > ITS_Study_Guide_V3_07_15_2021\test_WINNF_FT_S_BPR_2 is in the repository
> > MCP-01_T1_C00_Nov_14_test_7.config is in
> > \itsfs01\Projects\3_5GHzEscSasCertification\Files for Tranch1 (configs - study guide)\test_WINNF_FT_S_MCP_1
> > Would you like to rename it to MCP-01_T1_C00_West1_test_7.config?
> 
> It's upto you, I think the newer name is good.

Also, you can merge now(or after changing name) if you want

**Comment by jhazentia** [comment]
Looks good to me! @rdorchNTIA note the following:

- One file was renamed (see above comments). In the renamed file, there are ID/peer SAS hostName differences but shouldn't affect the test.
- There are additional tests in Published Study Guides\ITS_Study_Guide_V3_07_15_2021\test_WINNF_FT_S_MCP_1 that are not in Published Study Guides\ITS_Study_Guide_V2_11_29_2018\test_WINNF_FT_S_MCP_1. The additional tests I noticed are MCP-01_T1_C00_M_NYC-with-DPA-East7_5k_DP.config and MCP-01_T1_C00_M_NYC-with-DPA-East7_5k.config

**Review by jhazentia — APPROVED** [review]

**Comment by rdorchNTIA** [comment]
@jhazentia Re your comments above:
- One file was renamed (see above comments). In the renamed file, there are ID/peer SAS hostName differences but shouldn't affect the test.

o	okay

- There are additional tests in Published Study Guides\ITS_Study_Guide_V3_07_15_2021\test_WINNF_FT_S_MCP_1 that are not in Published Study Guides\ITS_Study_Guide_V2_11_29_2018\test_WINNF_FT_S_MCP_1. The additional tests I noticed are MCP-01_T1_C00_M_NYC-with-DPA-East7_5k_DP.config and MCP-01_T1_C00_M_NYC-with-DPA-East7_5k.config

o	MCP-01_T1_C00_M_NYC-with-DPA-East7_5k.config was used previously to ensure the SAS UUT could individually register, grant, and authorize 5k CBSDs.  It was run during T1 regression testing as ZZM.
o	MCP-01_T1_C00_M_NYC-with-DPA-East7_5k.config was added late in the previous testing to ensure the SAS UUT could respond to 5k CBSDs presented from a single Domain Proxy.  
o	I recommend keeping them in the Study Guide. A SAS UUT should successfully run both of these tests before attempting to run MCP-01_T1_C07_NYC-with-DPA-East7_59krev01.  We can discuss with our CRADA collaborators whether to include these two tests in regression testing once testing begins again.

**Review by rdorchNTIA — APPROVED** [review]

**Comment by jhazentia** [comment]
@cheroy-ntia, please change the P-DPA file back to version 1.0.6 since that is what will be used for Tranche 0-4 with the Python 2 test harness.

**Comment by RedaHossino** [comment]
no issue was found, RED approves those changes, nevertheless two general comments:

- the test "MCP-01_T1_C00_M_NYC-with-DPA-East7_5k" doesn't activate any DPA(so no chek will be performed by the test harness) and it adds the 5k CBSDs and their grants after the CPAS so even with an active DPA, it will only test the usage of daily DPA margin and not the MoveList algorithm, do you need to keep this test?

- some file names of the test configs were changed by adding "_M" or "_Mx", do we really need that? would that make the ITS need more effort later, for example if they want to compare the results of those same tests with previous results they have for SAS wave1?

**Review by jhazentia — APPROVED** [review]

**Pull request merged**
